### ISSUE TITLE
How can I read results of matmul?

### ISSUE THREAD

**Issue by june9713** [nineties/py-videocore#18]
Hello.
Thanks to you for great work and sharing your code.
Actually I dont know about assembly language well.
So Your code is very huge help for me.
Could you tell me how to read matmul result from gpu?
You show how to calculate matrix but there is no return.
I will wait your answer. Thanks!

**Comment by nineties** [comment]
Hello,

The results are written to the array C.
https://github.com/nineties/py-videocore/blob/master/examples/sgemm.py
Try insert
print(C)
at line 706.

Thank you.


2017年6月11日(日) 13:48 june9713 <notifications@github.com>:

**Comment by june9713** [comment]
Thanks for your fast answer. :-)
I've been in japan last year(tokyo) and
About 10 years ago in takamatz.
All of  ypur culture was great and especially food was really aswome. And a lot of kind nice person like ypu. I hope visit again soon. 
Thanks again. 
I hope always your plan will be come true in sucess.
:-)-----Original Message-----

**Comment by june9713** [comment]
Great!! Thanks! It works!

**Comment by nineties** [comment]
Your welcome.
