### ISSUE TITLE
execute /tests functions and print the Y results

### ISSUE THREAD

**Issue by SimonBataille** [nineties/py-videocore#38]
Hi,

I'm currently developing on VideoCore GPU and your project is really interesting.
Sadly I'm a totally Python beginner.

Could you send me a command-line to execute the  "test_per_elmt_imm()" function in "test_alu.py" and print the result in my raspberry terminal. I'm using a raspian lite OS.

Thanks :)

**Comment by Terminus-IMRC** [comment]
`nosetests -v tests/test_alu.py:test_per_elmt_imm`

**Comment by Terminus-IMRC** [comment]
(If you add `print` functions to `test_per_elmt_imm`, do `nosetests -v -s tests/test_alu.py:test_per_elmt_imm`.)

**Comment by SimonBataille** [comment]
Thank you a lot ;)
